from enum import Enum


class EventType(str, Enum):
    # Task
    TASK_CREATED = "TASK_CREATED"
    TASK_QUEUED = "TASK_QUEUED"
    TASK_STARTED = "TASK_STARTED"
    TASK_COMPLETED = "TASK_COMPLETED"
    TASK_FAILED = "TASK_FAILED"

    # Stage
    STAGE_STARTED = "STAGE_STARTED"
    STAGE_COMPLETED = "STAGE_COMPLETED"
    STAGE_FAILED = "STAGE_FAILED"

    # Agent
    AGENT_STARTED = "AGENT_STARTED"
    AGENT_COMPLETED = "AGENT_COMPLETED"
    AGENT_FAILED = "AGENT_FAILED"

    # Model
    MODEL_CALL_STARTED = "MODEL_CALL_STARTED"
    MODEL_CALL_COMPLETED = "MODEL_CALL_COMPLETED"
    MODEL_CALL_FAILED = "MODEL_CALL_FAILED"

    # Tool
    TOOL_CALL_STARTED = "TOOL_CALL_STARTED"
    TOOL_CALL_COMPLETED = "TOOL_CALL_COMPLETED"
    TOOL_CALL_FAILED = "TOOL_CALL_FAILED"

    # Test
    TEST_STARTED = "TEST_STARTED"
    TEST_COMPLETED = "TEST_COMPLETED"
    TEST_FAILED = "TEST_FAILED"

    # GitHub
    GITHUB_OPERATION_STARTED = "GITHUB_OPERATION_STARTED"
    GITHUB_OPERATION_COMPLETED = "GITHUB_OPERATION_COMPLETED"
    GITHUB_OPERATION_FAILED = "GITHUB_OPERATION_FAILED"

    # Security
    OWNERSHIP_LOST = "OWNERSHIP_LOST"
    AUTHORIZATION_DENIED = "AUTHORIZATION_DENIED"
    DANGEROUS_OPERATION_BLOCKED = "DANGEROUS_OPERATION_BLOCKED"
    PATH_VALIDATION_FAILED = "PATH_VALIDATION_FAILED"
    CREDENTIAL_SAFETY_FAILURE = "CREDENTIAL_SAFETY_FAILURE"

    # Worker
    WORKER_STARTED = "WORKER_STARTED"
    JOB_RECEIVED = "JOB_RECEIVED"
    JOB_CLAIMED = "JOB_CLAIMED"
    JOB_EXECUTION_STARTED = "JOB_EXECUTION_STARTED"
    JOB_EXECUTION_COMPLETED = "JOB_EXECUTION_COMPLETED"
    JOB_EXECUTION_FAILED = "JOB_EXECUTION_FAILED"
    JOB_LEASE_RENEWED = "JOB_LEASE_RENEWED"
    JOB_LEASE_LOST = "JOB_LEASE_LOST"
    JOB_RECLAIMED = "JOB_RECLAIMED"
    WORKER_SHUTDOWN = "WORKER_SHUTDOWN"

class AuditEventType(str, Enum):
    TASK_CREATED = "TASK_CREATED"
    TASK_EXECUTION_STARTED = "TASK_EXECUTION_STARTED"
    TASK_EXECUTION_COMPLETED = "TASK_EXECUTION_COMPLETED"
    TASK_EXECUTION_FAILED = "TASK_EXECUTION_FAILED"
    GITHUB_REPOSITORY_AUTHORIZED = "GITHUB_REPOSITORY_AUTHORIZED"
    GITHUB_REPOSITORY_DENIED = "GITHUB_REPOSITORY_DENIED"
    WEBHOOK_ACCEPTED = "WEBHOOK_ACCEPTED"
    WEBHOOK_REJECTED = "WEBHOOK_REJECTED"
    WEBHOOK_DEDUPLICATED = "WEBHOOK_DEDUPLICATED"
    AUTHORIZATION_DENIED = "AUTHORIZATION_DENIED"
    OWNERSHIP_LOST = "OWNERSHIP_LOST"
    DANGEROUS_OPERATION_BLOCKED = "DANGEROUS_OPERATION_BLOCKED"
    GITHUB_BRANCH_CREATED = "GITHUB_BRANCH_CREATED"
    GITHUB_PUSHED = "GITHUB_PUSHED"
    GITHUB_PR_CREATED = "GITHUB_PR_CREATED"
