"""Phase 1 Coding Agent.

Builds an OpenAI Agents SDK :class:`Agent` equipped with controlled workspace
tools.  The agent inspects the repository, plans minimal changes, applies
edits through the workspace manager, and validates via the test runner.

The agent receives no direct shell access.  All file I/O is mediated by
:class:`~app.workspace.manager.WorkspaceManager`.
"""

from __future__ import annotations

import logging
from typing import Any

from pydantic import BaseModel, Field

from agents import Agent, function_tool
from app.mcp.permissions import ToolPermission
from app.mcp.registry import registry
from app.schemas.task import PlanStep
from app.workspace.manager import WorkspaceManager
from app.workspace.runner import TestRunner

logger = logging.getLogger(__name__)

class AgentFinalOutput(BaseModel):
    """The structured final response from the coding agent."""
    plan: list[PlanStep] = Field(description="The actual sequence of steps you took to complete the task.")
    message: str = Field(description="Summary of changes made, test results, and any additional context.")

CODING_AGENT_INSTRUCTIONS = """\
You are CodeForge, a precise and disciplined software engineering agent.

You will be provided with a validated Implementation Plan generated by the Planning Engine.
Your primary goal is to implement this plan step-by-step.
If you encounter repository reality that contradicts the plan, you may adapt, but you MUST report any deviations in your final output.

Your workflow for every task:
1. INSPECT — list files and read the relevant source to understand the codebase.
2. IDENTIFY — locate the exact problem described in the task and plan.
3. PLAN — determine the minimal set of changes required to execute the implementation plan.
4. EDIT — apply changes using create_file or modify_file. Always write the COMPLETE file, not just the diff.
5. TEST — call run_tests to validate your changes.
6. REPORT — summarise what you changed and whether tests passed.

Mandatory rules:
- Never modify files that are not relevant to the task.
- Always read a file with read_file before editing it.
- When using modify_file, ALWAYS provide the COMPLETE updated file content, not just the diff. Make the smallest correct change. Do not refactor unrelated code.
- Always run tests after every edit cycle.
- If tests fail, report the failure honestly. Never claim success without passing tests.
- If you cannot determine what to change, say so clearly.
- Follow the coding style and conventions already present in the repository.
- Never delete files unless the task explicitly requires it.\
""".strip()






def _make_tools(workspace: WorkspaceManager, runner: TestRunner, permission: ToolPermission = ToolPermission.WRITE) -> list[Any]:
    """Return function tools wrapped from the MCP registry plus run_tests."""

    # Check which MCP tools this permission can see
    mcp_tools = registry.list_enabled_tools(permission)
    enabled_tool_names = {t.name for t in mcp_tools}

    # We create static wrappers for the core tools to satisfy openai-agents introspection.
    tools = []

    if "repository.list_files" in enabled_tool_names:
        @function_tool
        async def list_files(path: str = ".") -> str:
            """List files in the workspace."""
            res = await registry.execute_tool("repository.list_files", {"path": path}, permission, workspace=workspace)
            return res[0].text
        tools.append(list_files)

    if "repository.read_file" in enabled_tool_names:
        @function_tool
        async def read_file(path: str) -> str:
            """Read file content."""
            res = await registry.execute_tool("repository.read_file", {"path": path}, permission, workspace=workspace)
            return res[0].text
        tools.append(read_file)

    if "repository.search_files" in enabled_tool_names:
        @function_tool
        async def search_files(query: str, path: str = ".") -> str:
            """Search files in the workspace."""
            res = await registry.execute_tool("repository.search_files", {"query": query, "path": path}, permission, workspace=workspace)
            return res[0].text
        tools.append(search_files)

    if "repository.metadata" in enabled_tool_names:
        @function_tool
        async def get_metadata() -> str:
            """Get repository metadata."""
            res = await registry.execute_tool("repository.metadata", {}, permission, workspace=workspace)
            return res[0].text
        tools.append(get_metadata)

    if "git.status" in enabled_tool_names:
        @function_tool
        async def git_status() -> str:
            """Get Git branch, commit, and dirty status."""
            res = await registry.execute_tool("git.status", {}, permission, workspace=workspace)
            return res[0].text
        tools.append(git_status)

    if "repository.create_file" in enabled_tool_names:
        @function_tool
        async def create_file(path: str, content: str) -> str:
            """Create a new file."""
            res = await registry.execute_tool("repository.create_file", {"path": path, "content": content}, permission, workspace=workspace)
            return res[0].text
        tools.append(create_file)

    if "repository.modify_file" in enabled_tool_names:
        @function_tool
        async def modify_file(path: str, content: str) -> str:
            """Modify an existing file. Provide COMPLETE file content."""
            res = await registry.execute_tool("repository.modify_file", {"path": path, "content": content}, permission, workspace=workspace)
            return res[0].text
        tools.append(modify_file)

    if "repository.delete_file" in enabled_tool_names:
        @function_tool
        async def delete_file(path: str) -> str:
            """Delete a file."""
            res = await registry.execute_tool("repository.delete_file", {"path": path}, permission, workspace=workspace)
            return res[0].text
        tools.append(delete_file)

    @function_tool
    def run_tests() -> str:
        """Run the workspace test suite (pytest) and return pass/fail and output."""
        result = runner.run(workspace.root)
        logger.info("run_tests -> passed=%s exit_code=%d", result.passed, result.exit_code)
        lines = [f"PASSED: {result.passed}", f"Exit code: {result.exit_code}"]
        if result.stdout:
            lines.append(f"\nSTDOUT:\n{result.stdout}")
        if result.stderr:
            lines.append(f"\nSTDERR:\n{result.stderr}")
        return "\n".join(lines)
    tools.append(run_tests)

    return tools


def make_coding_agent(
    workspace: WorkspaceManager,
    runner: TestRunner,
    model: str = "gpt-4o",
) -> Agent:
    """Create and return an :class:`Agent` bound to *workspace* and *runner*.

    Args:
        workspace: The sandboxed file-system manager.
        runner: The controlled test executor.
        model: OpenAI model identifier to use.
    """
    tools = _make_tools(workspace, runner)
    logger.info("Creating coding agent with model=%s", model)
    return Agent(
        name="CodeForge Coding Agent",
        instructions=CODING_AGENT_INSTRUCTIONS,
        tools=tools,
        model=model,
        output_type=AgentFinalOutput,
    )
