"""Add lease_version to jobs

Revision ID: 1abea910462d
Revises: c61af4574cc6
Create Date: 2026-09-05 19:59:30.777527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1abea910462d'
down_revision: Union[str, None] = 'c61af4574cc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('lease_version', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'lease_version')
    # ### end Alembic commands ###
